#ifndef IG4U_MSGIDS_H
#define IG4U_MSGIDS_H

/**
 * @file ig4u_msgids.h
 * @brief iG4U 추력 유닛 cFS Message IDs
 */

#include "cfe.h"
#include "ig4u_topicids.h"

/* Command MIDs */
#define IG4U_CMD_MID        CFE_PLATFORM_CMD_TOPICID_TO_MIDV(CFE_MISSION_IG4U_CMD_TOPICID)
#define IG4U_WAKEUP_MID     CFE_PLATFORM_CMD_TOPICID_TO_MIDV(CFE_MISSION_IG4U_WAKEUP_TOPICID)

/* Telemetry MIDs */
#define IG4U_HK_TLM_MID       CFE_PLATFORM_TLM_TOPICID_TO_MIDV(CFE_MISSION_IG4U_HK_TLM_TOPICID)
#define IG4U_STATUS_TLM_MID   CFE_PLATFORM_TLM_TOPICID_TO_MIDV(CFE_MISSION_IG4U_STATUS_TLM_TOPICID)
#define IG4U_FIRE_RESULT_MID  CFE_PLATFORM_TLM_TOPICID_TO_MIDV(CFE_MISSION_IG4U_FIRE_RESULT_TOPICID)
#define IG4U_FAULT_LOG_MID    CFE_PLATFORM_TLM_TOPICID_TO_MIDV(CFE_MISSION_IG4U_FAULT_LOG_TOPICID)

#endif /* IG4U_MSGIDS_H */
